apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-node-1
  namespace: wipe
spec:
  restartPolicy: Never
  nodeName: talos-efz-8xy
  containers:
  - name: disk-wipe
    image: busybox
    securityContext:
      privileged: true
    # command: ["/bin/sh", "-c", "dd if=/dev/zero bs=1M count=100 oflag=direct of=/dev/sda"]
    command:
      - tail
      - "-f"
      - /dev/null
