apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-node-3
  namespace: wipe
spec:
  restartPolicy: Never
  nodeName: talos-yva-ttr
  containers:
  - name: disk-wipe
    image: busybox
    securityContext:
      privileged: true
    command: ["/bin/sh", "-c", "dd if=/dev/zero bs=1M count=100 oflag=direct of=/dev/sda && rm -rf /var/lib/rook/**"]
