apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.3.11
      helm:
        releaseName: argocd
        valuesObject:
          global:
            domain: argocd.apps.k8s1.cottage.my-lab.cz
          server:
            metrics:
              enabled: true
            ingress:
              enabled: true
              hosts: 
                - argocd.apps.k8s1.cottage.my-lab.cz
              tls:
              - hosts:
                  - argocd.apps.k8s1.cottage.my-lab.cz
                secretName: tls-argocd.my-lab.cz
              https: true
              ingressClassName: "nginx"
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            config:
              server.rbac.log.enforce.enable: "true"
              exec.enabled: "true" 
          applicationSet:
            enabled: false
          dex:
            enabled: false
          notifications:
            enabled: false 
          repoServer:
            metrics:
              enabled: true
          redis:
            metrics:
              enabled: true
          controller:
            metrics:
              enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true    