apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-certmanager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://charts.jetstack.io"
      chart: cert-manager
      targetRevision: 1.12.3
      helm:
        releaseName: certmanager
        valuesObject:
          installCRDs: true
          clusterResourceNamespace: certmanager
          extraArgs: 
            - '--dns01-recursive-nameservers-only'
            - '--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: certmanager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
