apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-emqx-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://repos.emqx.io/charts
      chart: emqx-operator
      targetRevision: 2.2.29
      helm:
        releaseName: emqx-operator
        valuesObject:
         metrics:
           enable: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: emqx-operator
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true    


