apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-homeassistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      path: infra/resources/homeassistant

    - repoURL: https://pajikos.github.io/home-assistant-helm-chart/
      targetRevision: 0.3.27
      chart: home-assistant
      helm:
        releaseName: home-assistant
        valuesObject:
          replicaCount: 1

          envFrom:
            - secretRef:
                name: secrets

          additionalVolumes:
            - name: entities-binary-sensors
              configMap:
                name: entities-binary-sensors
            - name: entities-numbers
              configMap:
                name: entities-numbers
            - name: entities-selects
              configMap:
                name: entities-selects
            - name: entities-sensors
              configMap:
                name: entities-sensors
            - name: entities-switches
              configMap:
                name: entities-switches
            - name: integrations-mqtt-sensors
              configMap:
                name: integrations-mqtt-sensors
            - name: integrations-influxdb
              configMap:
                name: integrations-influxdb

          additionalMounts:
            - mountPath: /custom-configurations/entities/binary_sensors
              name: entities-binary-sensors
            - mountPath: /custom-configurations/entities/numbers
              name: entities-numbers
            - mountPath: /custom-configurations/entities/selects
              name: entities-selects
            - mountPath: /custom-configurations/entities/sensors
              name: entities-sensors
            - mountPath: /custom-configurations/entities/switches
              name: entities-switches
            - mountPath: /custom-configurations/integrations/mqtt/sensors
              name: integrations-mqtt-sensors
            - mountPath: /custom-configurations/integrations/influxdb
              name: integrations-influxdb

          persistence:
            enabled: true
            accessMode: ReadWriteOnce
            size: 5Gi
            storageClass: "longhorn"

          ingress:
            enabled: true
            hosts:
              - host: home-assistant.apps.k8s1.cottage.my-lab.cz
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: http          
            tls:
              - hosts:
                  - home-assistant.apps.k8s1.cottage.my-lab.cz

          # addons:
          #   codeserver:
          #     enabled: true
          #     ingress:
          #       enabled: true
          #       hosts:
          #         - host: home-assistant-code.apps.k8s1.cottage.my-lab.cz
          #           paths:
          #             - path: /
          #               pathType: Prefix
          #               service:
          #                 name: main
          #                 port: http          
          #       tls:
          #         - hosts:
          #             - home-assistant-code.apps.k8s1.cottage.my-lab.cz

          configuration:
            enabled: true

            templateConfig: |-
              # Loads default set of integrations. Do not remove.
              default_config:

              http:
                use_x_forwarded_for: true
                trusted_proxies:
                  - 10.0.0.0/8
                  - 172.16.0.0/12
                  - 192.168.0.0/16
                  - 127.0.0.0/8

              homeassistant:
                name: Cottage
                unit_system: metric
                currency: CZK
                time_zone: "Europe/Prague"
                country: CZ                  

              # Load frontend themes from the themes folder
              frontend:
                themes: !include_dir_merge_named themes

              automation: !include automations.yaml
              script: !include scripts.yaml
              scene: !include scenes.yaml

              secrets: !include_dir_merge_list /custom-configurations/secrets

              binary_sensor: !include_dir_merge_list /custom-configurations/entities/binary_sensors
              number: !include_dir_merge_list /custom-configurations/entities/numbers
              select: !include_dir_merge_list /custom-configurations/entities/selects
              sensor: !include_dir_merge_list /custom-configurations/entities/sensors
              switch: !include_dir_merge_list /custom-configurations/entities/switches

              mqtt:
                # broker: !env_var MQTT_BROKER
                # port: !env_var MQTT_PORT
                # username: !env_var MQTT_USERNAME
                # password: !env_var MQTT_PASSWORD

                sensor: !include_dir_merge_list /custom-configurations/integrations/mqtt/sensors

              influxdb: !include_dir_merge_list /custom-configurations/integrations/influxdb

  destination:
    server: "https://kubernetes.default.svc"
    namespace: homeassistant
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true