apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-homeassistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      path: infra/resources/homeassistant

    - repoURL: https://pajikos.github.io/home-assistant-helm-chart/
      targetRevision: 0.3.34
      chart: home-assistant
      helm:
        releaseName: home-assistant
        valuesObject:
          securityContext:
            runAsUser: 0
            runAsGroup: 0       
             
          replicaCount: 1

          envFrom:
            - secretRef:
                name: secrets

          additionalVolumes:
            - name: entities-binary-sensors
              configMap:
                name: entities-binary-sensors
            - name: entities-numbers
              configMap:
                name: entities-numbers
            - name: entities-selects
              configMap:
                name: entities-selects
            - name: entities-sensors
              configMap:
                name: entities-sensors
            - name: entities-switches
              configMap:
                name: entities-switches

            - name: integrations-mqtt-binary-sensors
              configMap:
                name: integrations-mqtt-binary-sensors
            - name: integrations-mqtt-numbers
              configMap:
                name: integrations-mqtt-numbers
            - name: integrations-mqtt-selects
              configMap:
                name: integrations-mqtt-selects
            - name: integrations-mqtt-sensors
              configMap:
                name: integrations-mqtt-sensors
            - name: integrations-mqtt-switches
              configMap:
                name: integrations-mqtt-switches
                
            - name: integrations-influxdb
              configMap:
                name: integrations-influxdb

            - name: integrations-modbus
              configMap:
                name: integrations-modbus

         additionalMounts:
            - mountPath: /custom-configurations/entities/binary_sensors
              name: entities-binary-sensors
            - mountPath: /custom-configurations/entities/numbers
              name: entities-numbers
            - mountPath: /custom-configurations/entities/selects
              name: entities-selects
            - mountPath: /custom-configurations/entities/sensors
              name: entities-sensors
            - mountPath: /custom-configurations/entities/switches
              name: entities-switches

            - mountPath: /custom-configurations/integrations/mqtt/binary_sensors
              name: integrations-mqtt-binary-sensors
            - mountPath: /custom-configurations/integrations/mqtt/numbers
              name: integrations-mqtt-numbers
            - mountPath: /custom-configurations/integrations/mqtt/selects
              name: integrations-mqtt-selects
            - mountPath: /custom-configurations/integrations/mqtt/sensors
              name: integrations-mqtt-sensors
            - mountPath: /custom-configurations/integrations/mqtt/switches
              name: integrations-mqtt-switches
              
            - mountPath: /custom-configurations/integrations/influxdb
              name: integrations-influxdb

            - mountPath: /custom-configurations/integrations/modbus
              name: integrations-modbus

          persistence:
            enabled: true
            accessMode: ReadWriteOnce
            size: 50Gi
            storageClass: "longhorn"

          ingress:
            enabled: true
            className: nginx
            hosts:
              - host: home-assistant.apps.k8s1.cottage.my-lab.cz
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: http          
            tls:
              - hosts:
                  - home-assistant.apps.k8s1.cottage.my-lab.cz

          addons:
            codeserver:
              enabled: true
              auth:
                enabled: true
                existingSecret: "codeserver-secret"
              ingress:
                enabled: true
                className: nginx
                hosts:
                  - host: home-assistant-code.apps.k8s1.cottage.my-lab.cz
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: home-assistant-codeserver
                          port: codeserver          
                tls:
                  - hosts:
                      - home-assistant-code.apps.k8s1.cottage.my-lab.cz

          configuration:
            enabled: true

            templateConfig: |-
              # Loads default set of integrations. Do not remove.
              default_config:

              http:
                use_x_forwarded_for: true
                trusted_proxies:
                  - 10.0.0.0/8
                  - 172.16.0.0/12
                  - 192.168.0.0/16
                  - 127.0.0.0/8

              homeassistant:
                name: Cottage
                unit_system: metric
                currency: CZK
                time_zone: "Europe/Prague"
                country: CZ
                latitude: 49.2562599
                longitude: 15.1235941
                elevation: 574


              # Load frontend themes from the themes folder
              frontend:
                themes: !include_dir_merge_named themes

              automation: !include automations.yaml
              script: !include scripts.yaml
              scene: !include scenes.yaml

              # secrets: !include_dir_merge_list /custom-configurations/secrets

              binary_sensor: !include_dir_merge_list /custom-configurations/entities/binary_sensors
              number: !include_dir_merge_list /custom-configurations/entities/numbers
              select: !include_dir_merge_list /custom-configurations/entities/selects
              sensor: !include_dir_merge_list /custom-configurations/entities/sensors
              switch: !include_dir_merge_list /custom-configurations/entities/switches

              mqtt:
                # broker: !env_var MQTT_BROKER
                # port: !env_var MQTT_PORT
                # username: !env_var MQTT_USERNAME
                # password: !env_var MQTT_PASSWORD

                binary_sensor: !include_dir_merge_list /custom-configurations/integrations/mqtt/binary_sensors
                number: !include_dir_merge_list /custom-configurations/integrations/mqtt/numbers
                select: !include_dir_merge_list /custom-configurations/integrations/mqtt/selects
                sensor: !include_dir_merge_list /custom-configurations/integrations/mqtt/sensors
                switch: !include_dir_merge_list /custom-configurations/integrations/mqtt/switches

              influxdb: !include /custom-configurations/integrations/influxdb/settings.yaml

              template:
                - sensor: !include_dir_merge_list /custom-configurations/templates/sensors

              modbus: !include_dir_merge_list /custom-configurations/integrations/modbus


  destination:
    server: "https://kubernetes.default.svc"
    namespace: homeassistant
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true