apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-homeassistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      path: infra/resources/homeassistant

    - repoURL: https://pajikos.github.io/home-assistant-helm-chart/
      targetRevision: 0.3.27
      chart: home-assistant
      helm:
        releaseName: home-assistant
        valuesObject:
          replicaCount: 1

          additionalVolumes:
            - name: entities-binary-sensor
              configMap:
                name: entities-binary-sensor
            - name: entities-number
              configMap:
                name: entities-number
            - name: entities-select
              configMap:
                name: entities-select
            - name: entities-sensor
              configMap:
                name: entities-sensor
            - name: entities-switch
              configMap:
                name: entities-switch
            - name: entities-mqtt-sensor
              configMap:
                name: entities-mqtt-sensor

          additionalMounts:
            - mountPath: /custom-configurations/binary_sensor
              name: entities-binary-sensor
            - mountPath: /custom-configurations/number
              name: entities-number
            - mountPath: /custom-configurations/select
              name: entities-select
            - mountPath: /custom-configurations/sensor
              name: entities-sensor
            - mountPath: /custom-configurations/switch
              name: entities-switch
            - mountPath: /custom-configurations/mqtt/sensor
              name: entities-mqtt-sensor

          persistence:
            enabled: true
            accessMode: ReadWriteOnce
            size: 5Gi
            storageClass: "longhorn"

          ingress:
            enabled: true
            hosts:
              - host: home-assistant.apps.k8s1.cottage.my-lab.cz
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: http          
            tls:
              - hosts:
                  - home-assistant.apps.k8s1.cottage.my-lab.cz

          addons:
            codeserver:
              enabled: true
              ingress:
                enabled: true
                hosts:
                  - host: home-assistant-code.apps.k8s1.cottage.my-lab.cz
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: main
                          port: http          
                tls:
                  - hosts:
                      - home-assistant-code.apps.k8s1.cottage.my-lab.cz

          configuration:
            enabled: true

            templateConfig: |-
              # Loads default set of integrations. Do not remove.
              default_config:

              http:
                use_x_forwarded_for: true
                trusted_proxies:
                  - 10.0.0.0/8
                  - 172.16.0.0/12
                  - 192.168.0.0/16
                  - 127.0.0.0/8

              # Load frontend themes from the themes folder
              frontend:
                themes: !include_dir_merge_named themes

              automation: !include automations.yaml
              script: !include scripts.yaml
              scene: !include scenes.yaml

              binary_sensor: !include_dir_merge_list /custom-configurations/binary_sensor
              number: !include_dir_merge_list /custom-configurations/number
              select: !include_dir_merge_list /custom-configurations/select
              sensor: !include_dir_merge_list /custom-configurations/sensor
              switch: !include_dir_merge_list /custom-configurations/switch

              mqtt:
                sensor: !include_dir_merge_list /custom-configurations/mqtt/sensor

  destination:
    server: "https://kubernetes.default.svc"
    namespace: homeassistant
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true