apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-homeassistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      path: infra/resources/homeassistant

    - repoURL: https://pajikos.github.io/home-assistant-helm-chart/
      targetRevision: 0.3.37
      chart: home-assistant
      helm:
        releaseName: home-assistant
        valuesObject:
          securityContext:
            runAsUser: 0
            runAsGroup: 0       
             
          replicaCount: 1

          envFrom:
            - secretRef:
                name: secrets

          additionalVolumes:
            - name: ssh
              secret:
                secretName: ssh
                defaultMode: 0400

          additionalMounts:
            - mountPath: /root/.ssh
              name: ssh

          persistence:
            enabled: true
            accessMode: ReadWriteOnce
            size: 50Gi
            storageClass: "longhorn"

          ingress:
            enabled: true
            className: nginx
            hosts:
              - host: home-assistant.apps.k8s1.cottage.my-lab.cz
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: main
                      port: http          
            tls:
              - hosts:
                  - home-assistant.apps.k8s1.cottage.my-lab.cz

          addons:
            codeserver:
              enabled: true
              auth:
                enabled: true
                existingSecret: "codeserver-secret"
              ingress:
                enabled: true
                className: nginx
                hosts:
                  - host: home-assistant-code.apps.k8s1.cottage.my-lab.cz
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: home-assistant-codeserver
                          port: codeserver          
                tls:
                  - hosts:
                      - home-assistant-code.apps.k8s1.cottage.my-lab.cz
              additionalMounts:
                - mountPath: /root/.ssh
                  name: ssh

          configuration:
            enabled: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: homeassistant
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true