apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-influxdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "https://helm.influxdata.com/"
      chart: influxdb2
      targetRevision: 2.1.2
      helm:
        releaseName: influxdb
        valuesObject:
          adminUser:
            organization: stitnelab
            bucket: default
            user: mole-admin
            existingSecret: influxdb-admin-creds
          ingress:
            enabled: true
            tls: true
            hostname: influxdb.apps.k8s1.cottage.my-lab.cz
            className: nginx
            annotations:
              kubernetes.io/ingress.class: nginx
          persistence:
            enabled: true
            size: 20Gi
          env:
            - name: INFLUXDB_DB
              value: main

  destination:
    server: "https://kubernetes.default.svc"
    namespace: influxdb
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
