# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: infra-influxdb
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   sources:
#     - repoURL: https://github.com/xtrasolver/cottage-lab.git
#       targetRevision: HEAD
#       ref: repo
#     - repoURL: "https://helm.influxdata.com/"
#       chart: influxdb2
#       targetRevision: 2.1.1
#       helm:
#         releaseName: influxdb
#         valueFiles:
#           - $repo/infra/values/influxdb.yaml
#   destination:
#     server: "https://kubernetes.default.svc"
#     namespace: influxdb
#   syncPolicy:
#     automated: {}
#     syncOptions:
#       - CreateNamespace=true
