apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kubelet-serving-cert-approver
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      path: infra/resources/kubelet-serving-cert-approver
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubelet-serving-cert-approver
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true
