apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/longhorn/charts"
      targetRevision: pr-v1.6.0-rc2
      path: charts/longhorn
      helm:
        releaseName: longhorn
        valuesObject:
          ingress:
            enabled: true
            ingressClassName: "nginx"
            host: longhorn.apps.k8s1.cottage.my-lab.cz
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/auth-type: basic
              nginx.ingress.kubernetes.io/auth-secret: basic-auth
              nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'

  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn
  syncPolicy:
    automated: {}
    managedNamespaceMetadata:
      labels:
         pod-security.kubernetes.io/enforce: privileged    
    syncOptions:
      - CreateNamespace=true