apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-longhorn
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "https://charts.longhorn.io"
      targetRevision: v1.7.2
      chart: longhorn
      helm:
        releaseName: longhorn
        valuesObject:
          defaultSettings:
            backupTarget: "s3://longhorn-backup@minio/cottage"
            backupTargetCredentialSecret: "minio-secret"        
          persistence:
            defaultClassReplicaCount: 3
          ingress:
            enabled: true
            ingressClassName: "nginx"
            host: longhorn.apps.k8s1.cottage.my-lab.cz
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/auth-type: basic
              nginx.ingress.kubernetes.io/auth-secret: basic-auth
              nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      path: infra/resources/longhorn
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated: {}
    managedNamespaceMetadata:
      labels:
         pod-security.kubernetes.io/enforce: privileged    
    syncOptions:
      - CreateNamespace=true