apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-metrics-server
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://kubernetes-sigs.github.io/metrics-server
      chart: metrics-server
      targetRevision: 3.11.0
      helm:
        releaseName: metrics-server
        valueFiles:
          - $repo/infra/values/metrics-server.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics-server
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true    