apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 55.8.3
      helm:
        releaseName: prometheus-stack
        valuesObject:
          grafana:
            # persistence:
            #   type: pvc
            #   enabled: true
            #   storageClassName: openebs-jiva-csi-default
            #   accessModes:
            #     - ReadWriteOnce
            #   size: 1Gi
            ingress:
              enabled: true
              hosts:
                - grafana.apps.k8s1.cottage.my-lab.cz
              tls:
                - hosts:
                    - grafana.apps.k8s1.cottage.my-lab.cz
              ingressClassName: "nginx"
          nodeExporter:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus-stack
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true    
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
