apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-pylontech
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      path: charts/worker
      helm:
        releaseName: pylontech
        valuesObject:
          image:
            repository: xtrasolver/ha-pylontech
            pullPolicy: IfNotPresent
            tag: "0.0.15"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pylontech
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true