apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-rook-ceph
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      ref: repo
    - repoURL: "https://charts.rook.io/release"
      chart: rook-ceph
      targetRevision: 1.12.3
      helm:
        releaseName: rook-ceph
        valueFiles:
          - $repo/infra/values/rook-ceph.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
