apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-unifi-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/cottage-lab.git
      targetRevision: HEAD
      ref: repo
    - repoURL: "https://k8s-at-home.com/charts/"
      chart: unifi
      targetRevision: 5.1.2
      helm:
        releaseName: unifi-controller
        valueFiles:
          - $repo/infra/values/unifi-controller.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: unifi-controller
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
