substitutions:
  name: esp-32-poe
  friendly_name: esp-32-poe

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: esphome.mole-automation
    version: "1.0"

esp32:
  board: esp32-poe-iso
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password
  fast_connect: on

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp8266-01 Fallback Hotspot"
    password: !secret wifi_hotspot_password

logger:

# api:
#   encryption:
#     key: !secret api_token

mqtt:
  broker: 192.168.27.154
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic

sensor:
  - platform: uptime
    name: "Uptime"
    icon: mdi:clock-outline
    update_interval: 5s    