substitutions:
  name: esp-32-poe
  friendly_name: esp-32-poe

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: esphome.mole-automation
    version: "1.0"

esp32:
  board: esp32-poe-iso
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

logger:

# api:
#   encryption:
#     key: !secret api_token

mqtt:
  broker: 192.168.27.154
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  
# esp32_ble_tracker:
#   scan_parameters:
#     interval: 1100ms
#     window: 1100ms
#     active: true

# bluetooth_proxy:
#   active: true

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic

sensor:
  - platform: uptime
    name: "Uptime"
    icon: mdi:clock-outline
    update_interval: 5s    