# Just change name here
substitutions:
  device_name: "device_name-01"
  internal_name: device_name-01
  voltage_divider: "771"
  current_resistor: "0.0012"


esphome:
  name: ${internal_name}
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password
  fast_connect: on

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret wifi_hotspot_password

  manual_ip:
      static_ip: ${static_ip}
      gateway: 192.168.13.1
      subnet: 255.255.255.0
      dns1: 192.168.13.1
# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
# api:
#   encryption:
#     key:  !secret api_token

# ota:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
