- name: "Operating mode"
  platform: ghp
  state_topic: GHP/3/240/2000
  unique_id: "ghp/operating_mode"
  options:
    - Cooling
    - Heating
    - Auto
    - DHW
    - Cooling+DHW
    - Heating+DHW
  value_template: >
    {% set opmodes = ({1:"Cooling",2:"Heating",4:"Auto",8:"DHW",9:"Cooling+DHW",10:"Heating+DHW"}) %}
    {{ opmodes[value_json[0]] }}
  device:
    identifiers: ghp-mm10
    name: GHP-MM10
  command_topic: "GHP/set/240/2000"
  command_template: >
    {% set opmodes = ({1:"Cooling",2:"Heating",4:"Auto",8:"DHW",9:"Cooling+DHW",10:"Heating+DHW"}) %}
    {% for val in opmodes %}
    {% if loop.index == this.attributes.options.index(value)+1 %}
      {{ val }}
    {% endif %}
    {% endfor %}
