- name: "Service settings 1"
  state_topic: GHP/3/240/2100
  unique_id: "ghp/settings_1"
  device:
    identifiers: ghp-mm10
    name: GHP-MM10

- name: "Service settings 2"
  state_topic: GHP/3/240/2116
  unique_id: "ghp/settings_2"
  device:
    identifiers: ghp-mm10
    name: GHP-MM10

- name: "Service settings 3"
  state_topic: GHP/3/240/2132
  unique_id: "ghp/settings_3"
  device:
    identifiers: ghp-mm10
    name: GHP-MM10

- name: "Service settings 4"
  state_topic: GHP/3/240/2148
  unique_id: "ghp/settings_4"
  device:
    identifiers: ghp-mm10
    name: GHP-MM10

- name: "Service settings 5"
  state_topic: GHP/3/240/2164
  unique_id: "ghp/settings_5"
  device:
    identifiers: ghp-mm10
    name: GHP-MM10

- name: "Compressor operating frequency"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[0] }}"
  device_class: frequency
  unit_of_measurement: Hz
  unique_id: "ghp/Compressor-operating-frequency"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Electronic expansion valve opening"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[1] }}"
  device_class:
  unit_of_measurement: P
  unique_id: "ghp/Electronic-expansion-valve-opening"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Ambient temperature"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[2] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Ambient-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Outlet temperature"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[3] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Outlet-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Exhaust temperature"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[4] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Exhaust-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Suction temperature"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[5] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Suction-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Coil temperature"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[6] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Coil-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Expansion valve outlet temperature"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[7] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Expansion-valve-outlet-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Fan status"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[10] }}"
  device_class:
  unit_of_measurement:
  unique_id: "ghp/Fan-status"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "AC input current"
  state_topic: GHP/10/240/300
  value_template: "{{ value_json[15] }}"
  device_class: current
  unit_of_measurement: A
  unique_id: "ghp/AC-input-current"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Input voltage"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[0] * 10 }}"
  device_class: voltage
  unit_of_measurement: V
  unique_id: "ghp/Input-voltage"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Oil return state"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[1] }}"
  device_class:
  unit_of_measurement:
  unique_id: "ghp/Oil-return-state"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "DC bus voltage"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[4] }}"
  device_class: voltage
  unit_of_measurement: V
  unique_id: "ghp/DC-bus-voltage"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Compressor current"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[5] }}"
  device_class: current
  unit_of_measurement: A
  unique_id: "ghp/Compressor-current"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "PFC temperature"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[6] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/PFC-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "IPM temperature"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[7] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/IPM-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "DC fan speed-1"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[8] }}"
  device_class: volume_flow_rate
  unit_of_measurement: "%"
  unique_id: "ghp/DC-fan-speed-1"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "DC fan speed-2"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[9] }}"
  device_class: volume_flow_rate
  unit_of_measurement: "%"
  unique_id: "ghp/DC-fan-speed-2"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Economizer inlet temperature"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[10] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Economizer-inlet-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Economizer outlet temperature"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[11] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Economizer-outlet-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Water tank temperature/indoor temperature"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[12] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Water-tank-temperature/indoor-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Return water temperature"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[13] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/Return-water-temperature"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "EEV-2 opening 5"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[14] }}"
  device_class:
  unit_of_measurement: P
  unique_id: "ghp/EEV-2-opening-5"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "DC pump output"
  state_topic: GHP/10/240/316
  value_template: "{{ value_json[15] }}"
  device_class: volume_flow_rate
  unit_of_measurement: "%"
  unique_id: "ghp/DC-pump-output"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Low pressure saturation temperature"
  state_topic: GHP/10/240/332
  value_template: "{{ value_json[0] }}"
  device_class: temperature
  unit_of_measurement: °C
  unique_id: "ghp/"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Water inlet pressure"
  state_topic: GHP/10/240/332
  value_template: "{{ ( value_json[3] | int ) / 10 }}"
  device_class: pressure
  unit_of_measurement: bar
  unique_id: "ghp/Water-inlet-pressure"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Outlet pressure"
  state_topic: GHP/10/240/332
  value_template: "{{ ( value_json[4] | int ) / 10 }}"
  device_class: pressure
  unit_of_measurement: bar
  unique_id: "ghp/Outlet-pressure"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Feedback flow"
  state_topic: GHP/10/240/332
  value_template: "{{ value_json[5] / 10  }}"
  device_class: volume_flow_rate
  unit_of_measurement: m³/h
  unique_id: "ghp/Feedback-flow"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "Water pump Feedback PWM%"
  state_topic: GHP/10/240/332
  value_template: "{{ value_json[6] }}"
  device_class: volume_flow_rate
  unit_of_measurement: "%"
  unique_id: "ghp/Water-pump-Feedback-PWM"
  device:
    identifiers: ghp-mm10
    manufacturer: Grundig
    name: GHP-MM10
    model: MM10

- name: "AC temp diff (S1)"
  state_topic: GHP/3/240/2100
  value_template: "{{ value_json[0] }}"
  device_class: temperature
  unit_of_measurement: "°C"
  unique_id: "ghp/ac_temp_diff_s1"
  device:
    identifiers: ghp-mm10
    name: GHP-MM10

- name: "DHW temp diff (S2)"
  state_topic: GHP/3/240/2100
  value_template: "{{ value_json[1] }}"
  device_class: temperature
  unit_of_measurement: "°C"
  unique_id: "ghp/dhw_temp_diff_s2"
  device:
    identifiers: ghp-mm10
    name: GHP-MM10

- name: "Outlet temp diff (S89)"
  state_topic: GHP/3/240/2180
  value_template: "{{ value_json[8] }}"
  device_class: temperature
  unit_of_measurement: "°C"
  unique_id: "ghp/outlet_temp_diff_s89"
  device:
    identifiers: ghp-mm10
    name: GHP-MM10
