apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-wildcard-certificate
  namespace: certmanager
spec:
  commonName: '*.apps.k8s1.cottage.my-lab.cz'
  dnsNames:
  - '*.apps.k8s1.cottage.my-lab.cz'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cert-issuer
  secretName: tls-wildcard
