app-template:
  controllers:
    main:
      # annotations:
      #   reloader.stakater.com/auto: "true"
      type: statefulset
      # hack to make devices show as online
      # initContainers:
      #   01-init-config:
      #     image:
      #       repository: debian
      #       tag: 12.4-slim
      #     command:
      #       - /bin/sh
      #       - -c
      #     args:
      #       - >
      #         cp /original/config/* /config/
      containers:
        main:
          image:
            repository: ghcr.io/esphome/esphome
            tag: "2024.11.3"
          env:
            ESPHOME_DASHBOARD_USE_PING: "true"
            USERNAME: "admin"
            PASSWORD: "todo-1234"
          resources:
            requests:
              cpu: 10m
              memory: 1374M
            limits:
              memory: 2048M
  service:
    main:
      ports:
        http:
          port: 6052

  ingress:
    main:
      enabled: true
      className: nginx
      # annotations:
      #   external-dns.alpha.kubernetes.io/enabled: "true"
      #   cert-manager.io/cluster-issuer: letsencrypt-prod-dns
      #   # nginx.ingress.kubernetes.io/auth-url: https://auth.apps.k8s1.cottage.my-lab.cz/oauth2/auth
      #   # nginx.ingress.kubernetes.io/auth-signin: https://auth.apps.k8s1.cottage.my-lab.cz/oauth2/start
      hosts:
        - host: esphome.apps.k8s1.cottage.my-lab.cz
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - esphome.apps.k8s1.cottage.my-lab.cz

  # defaultPodOptions:
  #   nodeSelector:
  #     kubernetes.io/arch: amd64

  persistence:
    original-config:
      enabled: true
      type: custom
      globalMounts:
        - path: /original/config
      volumeSpec:
        name: all-in-one
        projected:
          sources:
            - configMap:
                name: esphome-config
            - secret:
                name: esphome-secrets
    target-config:
      enabled: true
      type: emptyDir
      globalMounts:
        - path: /config
    cache:
      enabled: true
      existingClaim: esphome-cache
      globalMounts:
        - path: /cache
    build:
      enabled: true
      existingClaim: esphome-build
      globalMounts:
        - path: /build
