apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  name: backup-02
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: true
  hooks: {}
  includedResources:
    - '*'
  itemOperationTimeout: 4h0m0s
  metadata: {}
  snapshotMoveData: false
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
    - default
