apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: regular-backup
  annotations:
    argocd.argoproj.io/sync-wave: "5"    
spec:
  schedule: "30 0 * * *"
  template:
    # labelSelector:
    #   matchExpressions:
    #   - {key: velero-backup, operator: In, values: ['true']}
    excludedNamespaces: []
    includedResources:
    - '*'
    storageLocation: default