apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  concurrency: 3
  cron: 15 13 * * *
  groups: []
  labels: {}
  name: snapshot-cleanup
  parameters: {}
  retain: 0
  task: snapshot-cleanup
