apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-delete
  namespace: longhorn-system
spec:
  concurrency: 3
  cron: 10 13 * * *
  groups:
    - default
  labels: {}
  name: snapshot-delete
  parameters: {}
  retain: 7
  task: snapshot-delete
