- name: "Heat Pump Temp Difference"
  unique_id: heat_pump_temp_diff
  unit_of_measurement: "°C"
  state: "{{ (states('sensor.esp32_poe_010_outlet_temp') | float(0) - states('sensor.esp32_poe_010_return_temp') | float(0)) | round(2)  }}"

- name: "Heat Pump Power"
  unique_id: heat_pump_heat_power
  unit_of_measurement: "W"
  state: "{{ (states('sensor.ghp_mm10_feedback_flow') | float(0) ) * 1163.0 * (states('sensor.heat_pump_temp_difference') | float(0)) }}"

- name: "Heat Pump Gain"
  unit_of_measurement: W
  unique_id: heat_pump_gain
  device_class: power
  state_class: measurement
  state: >
    {% if states('sensor.heat_pump_power') | float(0) >= 0 %}
        {{ states('sensor.heat_pump_power') | float(0) | abs }}
    {% else %}
        0
    {% endif %}

- name: "Heat Pump Loss"
  unit_of_measurement: W
  unique_id: heat_pump_loss
  device_class: power
  state_class: measurement
  state: >
    {% if states('sensor.heat_pump_power') | float(0) < 0 %}
        {{ states('sensor.heat_pump_power') | float(0) | abs }}
    {% else %}
        0
    {% endif %}
