apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-build
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
  volumeMode: Filesystem
