apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-build
  labels:
    recurring-job-group.longhorn.io/snapshot-delete=enabled
    recurring-job-group.longhorn.io/snapshot-cleanup=enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
  volumeMode: Filesystem
