server:
  ingress:
    enabled: true
    hosts: 
      - argocd.apps.k8s1.cottage.my-lab.cz
    tls:
    - hosts:
        - argocd.apps.k8s1.cottage.my-lab.cz
      secretName: tls-argocd.my-lab.cz
    https: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  config:
    server.rbac.log.enforce.enable: "true"
    exec.enabled: "true" 