adminUser:
  organization: stitnelab
  bucket: default
  user: mole-admin
  # existingSecret: influxdb-admin-creds
ingress:
  enabled: true
  tls: true
  seceretName: influxdb
  hostname: influxdb.apps.k8s1.cottage.my-lab.cz.my-lab.cz
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-cert-issuer"   
persistence:
  enabled: true
  size: 10Gi
env:
  - name: INFLUXDB_DB
    value: main
