ingress:
  enabled: true
  ingressClassName: "nginx"
  host: longhorn.apps.k8s1.cottage.my-lab.cz.my-lab.cz
  tlsSecret: tls-longhorn
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-cert-issuer"