grafana:
  # persistence:
  #   type: pvc
  #   enabled: true
  #   storageClassName: openebs-jiva-csi-default
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 1Gi
  ingress:
    enabled: true
    hosts:
      - grafana.apps.k8s1.cottage.my-lab.cz
    tls:
      - hosts:
          - grafana.apps.k8s1.cottage.my-lab.cz
    ingressClassName: "nginx"
nodeExporter:
  enabled: true