env:
  TZ: "Europe/Prague"
image:
  tag: v7.5.174
persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi    
mongodb:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi
  image:
    registry: docker.io
    repository: zcube/bitnami-compat-mongodb
    tag: 5.0.17-debian-11-r64
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
      - host: unifi-controller.apps.k8s1.cottage.my-lab.cz
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - unifi-controller.apps.k8s1.cottage.my-lab.cz  
service:
  main:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: unifi
    loadBalancerIP: 192.168.27.52
    externalTrafficPolicy: Local
    ports:
      stun:
        enabled: false
      syslog:
        enabled: false
      discovery:
        enabled: false
  udp:
    enabled: true
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: unifi
    loadBalancerIP: 192.168.21.52
    externalTrafficPolicy: Local
    ports:
      stun:
        enabled: true
        port: 3478
        protocol: UDP
      syslog:
        enabled: true
        port: 5514
        protocol: UDP
      discovery:
        enabled: true
        port: 10001
        protocol: UDP