apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emqx-crt
spec:
  secretName: emqx-crt-secret
  dnsNames:
  - emqx.k8s1.cottage.my-lab.cz
  issuerRef:
    name: letsencrypt-cert-issuer
    kind: ClusterIssuer
    group: cert-manager.io