apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.8.6
  coreTemplate:
    spec:
      replicas: 3
      volumeClaimTemplates:
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce

      envFrom:
        - secretRef:
            name: emqx-admin

      extraVolumes:
        - name: emqx-tls
          secret:
            secretName: emqx-crt-secret
        - name: init-user
          secret:
            secretName: emqx-init-user

      extraVolumeMounts:
        - name: emqx-tls
          mountPath: /mounted/cert
        - name: init-user
          mountPath: /opt/init-user.json
          subPath: init-user.json
          readOnly: true
        - name: init-user
          mountPath: /opt/init-acl
          subPath: init-acl
          readOnly: true

  dashboardServiceTemplate:
    spec:
      type: ClusterIP
  listenersServiceTemplate:
    spec:
      type: LoadBalancer
      loadBalancerIP: 192.168.21.51
  config:
    data: |
      authentication {
        backend = "built_in_database"
        mechanism = "password_based"
        password_hash_algorithm {
            name = "bcrypt"
        }
        user_id_type = "username"
        bootstrap_file = "/opt/init-user.json"
        bootstrap_type = "plain"
      }
      authorization {
        sources = [
          {
            type = built_in_database
            enable = true
          }
          {
            type = file
            path = "/opt/init-acl"
          }
        ]
        no_match: "deny"
      }    
      # authentication {
      #     mechanism = password_based
      #     backend = http
      #     enable = true
      #
      #     method = get
      #     url = "http://{{ .Values.mqtt.bridge.url }}:{{ .Values.mqtt.bridge.port }}/auth"
      #     body {
      #         username = "${username}"
      #         password = "${password}"
      #     }
      #     headers {
      #         "X-Request-Source" = "EMQX"
      #     }
      # }
      # authorization {
      #     sources = [
      #     {
      #         type = http
      #         enable = true
      #     
      #         method = get
      #         url = "http://{{ .Values.mqtt.bridge.url }}:{{ .Values.mqtt.bridge.port }}/acl"
      #         body {
      #             username = "${username}"
      #             topic = "${topic}"
      #         }
      #         headers {
      #             "X-Request-Source" = "EMQX"
      #         }
      #     }
      #     ]
      #     no_match = allow
      #     deny_action = ignore
      #     cache {
      #     enable = true
      #     max_size = 32
      #     ttl = 1m
      #     }
      # }
      listeners.ssl.default {
          bind = "0.0.0.0:8883"
          ssl_options {
              cacertfile = "/mounted/cert/ca.crt"
              certfile = "/mounted/cert/tls.crt"
              keyfile = "/mounted/cert/tls.key"
              gc_after_handshake = true
              handshake_timeout = 5s
          }
      }
